apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector: { matchLabels: { app: myapp } }
  template:
    metadata: { labels: { app: myapp } }
    spec:
      containers:
        - name: app
          image: ghcr.io/ORG/myapp-crud:latest
          ports: [{ containerPort: 8000 }]
          readinessProbe: { httpGet: { path: /readyz, port: 8000 }, initialDelaySeconds: 2 }
          livenessProbe:  { httpGet: { path: /healthz, port: 8000 }, initialDelaySeconds: 2 }
