services:
  postgres:
    image: postgres:15
    container_name: gajogagu_postgres
    env_file:
      - docker-compose.env
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gajogagu -d gajogagu_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  crud:
    build:
      context: ../..
      dockerfile: docker/crud.Dockerfile
    image: ghcr.io/gajogagu/myapp-crud:latest
    container_name: gajogagu_crud_api
    env_file:
      - docker-compose.env
    ports: 
      - "8001:8000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  crud-tests:
    build:
      context: ../..
      dockerfile: docker/crud.Dockerfile
    image: ghcr.io/gajogagu/myapp-crud:latest
    container_name: gajogagu_crud_tests
    env_file:
      - docker-compose.env
    depends_on:
      postgres:
        condition: service_healthy
    command: ["python", "-m", "pytest", "-q"]
    restart: "no"

volumes:
  postgres_data:
