services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: gajogagu_db
      POSTGRES_USER: gajogagu
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gajogagu -d gajogagu_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  crud:
    build:
      context: ../..
      dockerfile: docker/crud.Dockerfile
    image: ghcr.io/gajogagu/myapp-crud:latest
    ports: ["8001:8000"]
    environment:
      - LOG_LEVEL=INFO
      - DATABASE_URL=postgresql://gajogagu:password@postgres:5432/gajogagu_db
    depends_on:
      postgres:
        condition: service_healthy

  dl:
    build:
      context: ../..
      dockerfile: docker/dl.Dockerfile
    image: ghcr.io/gajogagu/myapp-dl:latest
    container_name: gajogagu_dl_api
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    runtime: nvidia
    ports:
      - "8002:8000"
    environment:
      - DETECTION_CONFIDENCE_THRESHOLD=0.7
      - DEFAULT_TOP_K=5
      - LOG_LEVEL=INFO
      - TF_ENABLE_ONEDNN_OPTS=0
      - DATABASE_URL=postgresql://gajogagu:password@postgres:5432/gajogagu_db
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data:
