apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-dl
spec:
  template:
    spec:
      nodeSelector:
        accelerator: nvidia   # adjust to your cluster
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: app
          image: ghcr.io/ORG/myapp-dl:latest
          resources:
            limits:
              nvidia.com/gpu: "1"
            requests:
              cpu: "500m"
              memory: "1Gi"
