openapi: 3.0.3
info: { title: DL Inference API, version: "1.0.0" }
paths:
  /infer:
    post:
      summary: Run inference
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InferIn'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InferOut'
components:
  schemas:
    InferIn:
      type: object
      properties: { text: { type: string } }
      required: [text]
    InferOut:
      type: object
      properties: { score: { type: number, format: float } }
      required: [score]
