name: Build & Push Images
on:
  push:
    branches: [ main ]
    paths:
      - 'services/**'
      - 'docker/**'
      - '.github/workflows/docker-build.yml'
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: crud
            dockerfile: docker/crud.Dockerfile
            image: ghcr.io/gajogagu/myapp-crud:latest
            context: .
            pathFilter: 'services/crud-api/**'
          - name: dl
            dockerfile: docker/dl.Dockerfile
            image: ghcr.io/gajogagu/myapp-dl:latest
            context: .
            pathFilter: 'services/dl-api/**'
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changed:
              - ${{ matrix.pathFilter }}
              - 'docker/**'
              - 'libs/shared/**'
      - if: steps.filter.outputs.changed == 'true'
        uses: docker/setup-buildx-action@v3
      - if: steps.filter.outputs.changed == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - if: steps.filter.outputs.changed == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.image }}
